---

- name: Ensure Cantaloupe properties directory exists
  file:
    path: "{{ cantaloupe_symlink }}"
    state: directory
    owner: "{{ cantaloupe_user }}"
    group: "{{ cantaloupe_group }}"
    mode: "0755"

- name: Template Cantaloupe Properties
  template:
    src: cantaloupe.properties.j2
    dest: "{{ cantaloupe_symlink }}/cantaloupe.properties"
    owner: "{{ cantaloupe_user }}"
    group: "{{ cantaloupe_group }}"
    mode: "0644"
