---

- name: Kakaku home
  file:
    path: "/opt/kakadu"
    owner: "{{ cantaloupe_user }}"
    group: "{{ cantaloupe_group }}"
    recurse: yes
    state: directory

- name: Get Kakadu
  unarchive:
    remote_src: yes
    src: https://alpha.library.yorku.ca/kakadu.tar.gz
    dest: /opt/kakadu
    owner: "{{ cantaloupe_user }}"
    group: "{{ cantaloupe_group }}"

- name: Kakaku libraries (ldconfig)
  template:
    src: ldconfig.kakadu.conf
    dest: /etc/ld.so.conf.d/kakadu.conf

- name: Update ldconfig
  command: "ldconfig"

- name: Install Cantaloupe
  unarchive:
    remote_src: yes
    src: https://github.com/medusa-project/cantaloupe/releases/download/v{{ cantaloupe_version }}/cantaloupe-{{ cantaloupe_version }}.zip
    dest: "{{ cantaloupe_install_root }}"
    owner: "{{ cantaloupe_user }}"
    group: "{{ cantaloupe_group }}"
    creates: "{{ cantaloupe_install_root }}/cantaloupe-{{ cantaloupe_version }}"

- name: Remove temporary Canatloupe directory
  file:
    path: /opt/cantaloupe
    state: absent

- name: Create Cantaloupe symlink
  file:
    state: link
    src: "{{ cantaloupe_install_root }}/cantaloupe-{{ cantaloupe_version }}"
    dest: "{{ cantaloupe_symlink }}"
    owner: "{{ cantaloupe_user }}"
    group: "{{ cantaloupe_group }}"

- name: Create Cantaloupe log path
  file:
    state: directory
    path: "{{ cantaloupe_log_path }}"
    owner: "{{ cantaloupe_user }}"
    group: "{{ cantaloupe_group }}"

- name: Setup libjpeg-turbo library
  file:
    state: directory
    path: /opt/libjpeg-turbo/lib/
    owner: "{{ cantaloupe_user }}"
    group: "{{ cantaloupe_group }}"

- name: Setup libjpeg-turbo library symlink
  file:
    state: link
    src: /usr/lib/x86_64-linux-gnu/libturbojpeg.so
    dest: /opt/libjpeg-turbo/lib/libturbojpeg.so
    owner: "{{ cantaloupe_user }}"
    group: "{{ cantaloupe_group }}"
