name: Ansible Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install ansible-lint
      run: |
          python -m pip install --upgrade pip
          pip install ansible-lint==4.3.7
    - name: Run ansible-lint
      run: |
        ansible-lint
