---
crayfish_version_tag: dev
crayfish_db: "{{ claw_db }}"

crayfish_fedora_base_url: "http://10.0.0.16:8080/fcrepo/rest"
crayfish_drupal_base_url: "https://gamma.library.yorku.ca"
crayfish_log_directory: "/var/log/islandora"
