ansible_python_interpreter: /usr/bin/python

mysql_root_username: root
mysql_root_password: "{{ islandora_db_root_password }}"

mysql_key_buffer_size: 0
mysql_join_buffer_size: 393216
mysql_innodb_buffer_pool_size: "1024M"
mysql_innodb_log_file_size: "32M"
mysql_skip_name_resolve: true
