---

- name: Clone CLAW Alpaca
  git:
    repo: https://github.com/whikloj/Alpaca.git
    dest: "{{ alpaca_clone_directory }}"
    version: "{{ alpaca_version }}"
  register: alpaca_git

- name: Install Alpaca via Gradle
  command: ./gradlew build shadowJar
  args:
    chdir: "{{ alpaca_clone_directory }}"
  when: alpaca_git.changed
