---

- include_tasks: compile.yml
  tags:
    - alpaca
    - alpaca-compile
  when: alpaca_from_source

- include_tasks: download.yml
  tags:
    - alpaca
    - alpaca-download
  when: not alpaca_from_source

- include_tasks: config.yml
  tags:
    - alpaca
    - alpaca-config
