---

- include: compile.yml
  tags:
    - alpaca
    - alpaca-compile
  when: alpaca_from_source

- include: download.yml
  tags:
    - alpaca
    - alpaca-download
  when: not alpaca_from_source

- include: config.yml
  tags:
    - alpaca
    - alpaca-config
