---
composer_version: "2.1.14"
composer_version_branch: ""
composer_keep_updated: no
drupal_build_composer_project: true
drupal_composer_install_dir: /var/www/html/drupal
drupal_composer_project_options: "--prefer-dist --no-interaction"
drupal_core_owner: "{{ ansible_user }}"
drupal_composer_dependencies:
  - "drupal/devel:^4.0"
  - "drush/drush:^10.3"
  - "drupal/restui:^1.20"
  - "drupal/search_api_solr:^4.2"
  - "drupal/facets:^2"
  - "drupal/matomo:^1.19"
  - "drupal/pdf:^1.1"
  - "drupal/admin_toolbar:^3.1"
  - "drupal/rest_oai_pmh:^2.0@beta"
  - "drupal/transliterate_filenames:^2.0"
  - "easyrdf/easyrdf:^1.1"
  - "drupal/context:^4.0@beta"
  - "drupal/flysystem:^2@beta"
  - "drupal/group:^1.4"
  - "islandora/islandora:^2.4"
  - "--with-all-dependencies yorkulibraries/yudl_defaults:2.x-dev islandora/openseadragon:^2 islandora/controlled_access_terms:^2"
  - "islandora-rdm/islandora_fits:dev-8.x-1.x"
  - "drupal/ldap:^4.0@alpha"
  - "drupal/paragraphs:^1.12"
  - "drupal/bootstrap_barrio:^5.5"
  - "drupal/simple_sitemap:^3.10"
  - "drupal/pathauto:^1.8"
  - "drupal/views_bulk_operations:^4.0"
  - "drupal/views_bulk_edit:^2.6"
  - "drupal/search_api_autocomplete"
  - "mjordan/islandora_repository_reports:dev-main"
  - "mjordan/islandora_workbench_integration:dev-main"
drupal_composer_project_package: "drupal/recommended-project:^9.1@stable"
drupal_core_path: "{{ drupal_composer_install_dir }}/web"
drupal_db_user: drupal
drupal_db_name: drupal
drupal_db_backend: "{{ claw_db }}"
drupal_db_host: "127.0.0.1"
drupal_domain: "omega.library.yorku.ca"
drupal_site_name: "York University Digital Library"
drupal_install_profile: standard
drupal_account_name: admin
drupal_enable_modules:
  - rdf
  - responsive_image
  - syslog
  - serialization
  - basic_auth
  - rest
  - restui
  - devel
  - search_api_solr
  - facets
  - matomo
  - pdf
  - admin_toolbar
  - transliterate_filenames
  - islandora_defaults
  - controlled_access_terms_defaults
  - islandora_defaults
  - islandora_fits
  - islandora_breadcrumbs
  - islandora_iiif
  - islandora_oaipmh
  - islandora_search
  - ldap_authentication
  - ldap_user
  - paragraphs
  - simple_sitemap
  - pathauto
  - views_bulk_operations
  - views_bulk_edit
  - islandora_repository_reports
  - islandora_workbench_integration
  - islandora_mirador
  - islandora_repository_reports_log
  - islandora_repository_reports_oai_usage
  - islandora_repository_reports_matomo
  - islandora_repository_reports_activemq
  - search_api_autocomplete
  - search_api_solr_autocomplete
  - geolocation_leaflet
  - config_translation
  - locale
  - group
drupal_trusted_hosts:
  - ^localhost$
  - "omega.library.yorku.ca"
drupal_trusted_hosts_file: "{{ drupal_core_path }}/sites/default/settings.php"
drupal_public_filesystem: "{{ drupal_core_path }}/sites/default/files"
drupal_external_libraries_directory: "{{ drupal_core_path }}/libraries"
fedora_base_url: "http://omega.library.yorku.ca:8080/fcrepo/rest/"
drupal_jsonld_remove_format: true
drupal_gemini_pseudo_bundles:
  - islandora_object:node
  - image:media
  - file:media
  - audio:media
  - video:media
openseadragon_composer_item: "islandora/openseadragon:2.x-dev"
