---

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define tomcat_home
  set_fact:
    tomcat_home: "{{ __tomcat_home }}"
  when: tomcat_home is not defined

- name: Define tomcat_version
  set_fact:
    tomcat_version: "{{ __tomcat_version }}"
  when:
    - tomcat_version is not defined
    - __tomcat_version is defined

- name: Define tomcat_binary_url
  set_fact:
    tomcat_binary_url: "{{ __tomcat_binary_url }}"
  when:
    - tomcat_binary_url is not defined
    - __tomcat_binary_url is defined

- name: Define tomcat_target_dir
  set_fact:
    tomcat_target_dir: "{{ __tomcat_target_dir }}"
  when:
    - tomcat_target_dir is not defined
    - __tomcat_target_dir is defined
