---

- hosts: webserver
  become: yes

  tasks:
    - name: Install certbot snap
      snap:
        name: certbot
        classic: yes
      when: env == "staging" or env == "production"

    - name: Symlink certbot executable
      file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        state: link
      when: env == "staging" or env == "production"

    - name: Stop Apache to install certificates
      service:
        name: apache2
        state: stopped
      when: env == "staging" or env == "production"

    - name: Certbot setup
      command: certbot --apache certonly --agree-tos --email "{{ certbot_admin_email }}" --noninteractive -d "{{ drupal_domain }}"
      when: env == "staging" or env == "production"

    - name: Add https config
      template:
        src: omega.islandora-le-ssl.conf.j2
        dest: "{{ apache_conf_path }}/sites-available/islandora-le-ssl.conf"
        owner: root
        group: root
        mode: 0644
      when: env == "staging" or env == "production"

    - name: Add omega http config
      template:
        src: omega.islandora.conf.j2
        dest: "{{ apache_conf_path }}/sites-available/islandora.conf"
        owner: root
        group: root
        mode: 0644
      when: env == "staging" or env == "production"

    - name: Enable https site
      command: a2ensite islandora-le-ssl.conf
      when: env == "staging" or env == "production"

    - name: Start Apache
      service:
        name: apache2
        state: started
      when: env == "staging" or env == "production"
