---

- hosts: crayfish
  become: yes

  vars:
    php_version: "8.0"

  roles:
    - geerlingguy.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.git
    - geerlingguy.composer
    - Islandora-Devops.crayfish
