---

- name: Setup, configure, and install Crayfish
  hosts: crayfish
  become: true

  vars:
    php_version: "8.3"
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - geerlingguy.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.git
    - geerlingguy.composer
    - Islandora-Devops.crayfish
