---

- hosts: crayfish
  become: yes

  vars:
    php_version: "7.4"

  roles:
    - Islandora-Devops.grok
    - geerlingguy.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.git
    - geerlingguy.composer
    - Islandora-Devops.crayfish
