---

- hosts: all
  become: yes

  pre_tasks:
    - set_fact: # noqa 502
        claw_db: 'mysql'
      when: claw_db is not defined
      tags:
        - always

  roles:
    - role: geerlingguy.mysql
      when: claw_db == 'mysql'
