---

- name: Setup, configure, and install MySQL
  hosts: all
  become: true

  pre_tasks:
    - set_fact:
        claw_db: 'mysql'
      when: claw_db is not defined
      tags:
        - always

  roles:
    - role: geerlingguy.mysql
      when: claw_db == 'mysql'

  post_tasks:
    - name: Ensure MySQL service is running and enabled
      service:
        name: mysql
        state: started
        enabled: true
      when: claw_db == 'mysql'
      tags:
        - mysql
        - service
