---

- hosts: webserver
  become: yes

  # add some vars here so we can run with --start-at-task if desired
  vars:
    webserver_app_user: "www-data"
    vagrant_user: "vagrant"

  tasks:

    - name: Get york_drupal_theme
      git:
        repo: https://github.com/yorkulibraries/york_drupal_theme.git
        dest: "{{ drupal_core_path }}/themes/custom/york_drupal_theme"
        version: member-block-fix
        force: yes

    - name: Chown york_drupal_theme
      file:
        dest: "{{ drupal_core_path }}/themes/custom/york_drupal_theme"
        state: directory
        owner: "{{ webserver_app_user }}"
        group: "{{ webserver_app_user }}"
        mode: 0775
        recurse: yes

    - name: Enable york_drupal_theme
      command: "drush --root={{ drupal_core_path }} -y theme:enable york_drupal_theme"

    - name: Set york_drupal_theme default
      command: "drush --root={{ drupal_core_path }} -y cset system.theme default york_drupal_theme"

    - name: Clear cache
      command: "drush --root={{ drupal_core_path }} -y cr"
