---

- hosts: webserver
  become: yes

  # add some vars here so we can run with --start-at-task if desired
  vars:
    webserver_app_user: "www-data"
    vagrant_user: "vagrant"

  tasks:
    - name: Set MySQL transaction isolation level #https://www.drupal.org/docs/system-requirements/setting-the-mysql-transaction-isolation-level
      command: "mysql -u root drupal -e 'SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED'"

    - name: Get jquery-ui-slider-pips
      git:
        repo: https://github.com/simeydotme/jQuery-ui-Slider-Pips.git
        dest: "{{ drupal_core_path }}/libraries/jquery-ui-slider-pips"
        version: master
        force: yes

    - name: Get Islandora PREMIS
      git:
        repo: https://github.com/mjordan/islandora_premis.git
        dest: "{{ drupal_core_path }}/modules/contrib/islandora_premis"
        version: 8.x-1.x
        force: yes

    - name: Enable Islandora PREMIS # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y en islandora_premis"

    - name: Get Islandora Workbench
      git:
        repo: https://github.com/mjordan/islandora_workbench.git
        dest: "/opt/islandora_workbench"
        version: ad6c9546d785d296a0b12695231b36a1dae994a5
        force: yes

    - name: Install Islandora Workbench dependencies
      shell: "cd /opt/islandora_workbench; python setup.py install"

    - name: Create workbench env
      file:
        path: "/opt/workbench/{{ item }}"
        owner: "{{ vagrant_user }}"
        group: "{{ vagrant_user }}"
        recurse: yes
        state: directory
      with_items: ["configs", "logs", "data"]

    - name: Get YUDL collections workbench configs
      template:
        src: "yudl-collections-{{ item }}.yml"
        owner: "{{ vagrant_user }}"
        group: "{{ vagrant_user }}"
        dest: /opt/workbench/configs
      with_items: ["00", "01", "02", "03", "04", "06", "07", "08", "09"]

    - name: Get sample data workbench configs
      template:
        src: "{{ item }}.yml"
        owner: "{{ vagrant_user }}"
        group: "{{ vagrant_user }}"
        dest: /opt/workbench/configs
      with_items: ["paged", "single", "collection-image", "contact_categories"]
      when: env != "staging" or env != "production"

    - name: Get sample data
      unarchive:
        remote_src: yes
        src: http://alpha.library.yorku.ca/sample-data.zip
        owner: "{{ vagrant_user }}"
        group: "{{ vagrant_user }}"
        dest: /opt/workbench/data
      when: env != "staging" or env != "production"

    - name: Add admin to fedoraAdmin role # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y urol fedoraadmin admin"

    # Set jsonld module to strip ?_format=jsonld
    - name: Set JSONLD Config # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y cset --input-format=yaml jsonld.settings remove_jsonld_format {{ drupal_jsonld_remove_format }}"

    - name: Set broker_url (PRODUCTION) # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y cset islandora.settings broker_url 'tcp://10.0.0.16:61613'"
      when: env == "production"

    - name: Set JWT Expiry # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y cset islandora.settings jwt_expiry '{{ islandora_jwt_expiry }}'"

    - name: Set pseudo field bundles # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y cset --input-format=yaml islandora.settings gemini_pseudo_bundles.{{ item.0 }} {{ item.1 }}"
      with_indexed_items: "{{ drupal_gemini_pseudo_bundles }}"

    - name: Set media urls # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y cset --input-format=yaml media.settings standalone_url true"

    - name: Set iiif url # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y cset --input-format=yaml islandora_iiif.settings iiif_server {{ openseadragon_iiiv_server }}"

    - name: Set iiif manifest view # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y cset --input-format=yaml openseadragon.settings manifest_view iiif_manifest"

    - name: Set OpenSeadragon reference strip  # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y cset --input-format=yaml openseadragon.settings viewer_options.showReferenceStrip true"

    - name: Set OpenSeadragon viewport  # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y cset --input-format=yaml openseadragon.settings viewer_options.preserveViewport true"

    - name: Set OpenSeadragon overlays  # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y cset --input-format=yaml openseadragon.settings viewer_options.preserveOverlays true"

    - name: Run Islandora migration # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} --userid=1 mim islandora_tags"

    - name: Run Islandora FITS migration # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} --userid=1 mim islandora_fits_tags"

    - name: Run York migration # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} --userid=1 mim islandora_defaults_00_tags,islandora_defaults_01_rights,islandora_defaults_02_access,islandora_defaults_03_languages,islandora_defaults_04_physical_form,islandora_defaults_05_genre,islandora_defaults_06_continent,islandora_defaults_07_country,islandora_defaults_08_province,islandora_defaults_09_region,islandora_defaults_10_county,islandora_defaults_11_city,islandora_defaults_12_city_section,islandora_defaults_13_corporate_body,islandora_defaults_14_person,islandora_defaults_15_subjects"

    - name: Islandora Groups configuration # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} cset islandora_group.config restricted islandora_access"

    - name: Islandora Groups configuration # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} cset islandora_group.config york_university islandora_access"

    - name: Islandora Groups configuration # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} cset islandora_group.config media-type-access-fields.audio field_access_terms"

    - name: Islandora Groups configuration # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} cset islandora_group.config media-type-access-fields.document field_access_terms"

    - name: Islandora Groups configuration # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} cset islandora_group.config media-type-access-fields.extracted_text field_access_terms"

    - name: Islandora Groups configuration # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} cset islandora_group.config media-type-access-fields.file field_access_terms"

    - name: Islandora Groups configuration # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} cset islandora_group.config media-type-access-fields.image field_access_terms"

    - name: Islandora Groups configuration # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} cset islandora_group.config media-type-access-fields.remote_video field_access_terms"

    - name: Islandora Groups configuration # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} cset islandora_group.config media-type-access-fields.video field_access_terms"

    - name: Islandora Groups configuration # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} cset islandora_group.config node-type-access-fields.islandora_object field_access_terms"

    - name: Add mov to video formats # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} cset field.field.media.video.field_media_video_file settings.file_extensions 'mp4 mov'"

    - name: Set site email # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} cset system.site mail {{ certbot_admin_email }}"
      when: env == "staging" or env == "production"

    - name: Set update notifications email # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} cset update.settings notification.emails {{ certbot_admin_email }}"
      when: env == "staging" or env == "production"

    - name: Set admin only account creation # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} cset user.settings register admin_only"

    - name: Add admin users # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} ucrt {{ item }}"
      loop: "{{ lookup('file', 'templates/list_of_admin_users').splitlines() }}"

    - name: Add islandora admin users # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} ucrt {{ item }}"
      loop: "{{ lookup('file', 'templates/list_of_islandora_admin_users').splitlines() }}"

    - name: Add islandora creator users # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} ucrt {{ item }}"
      loop: "{{ lookup('file', 'templates/list_of_islandora_creator_users').splitlines() }}"

    - name: Add past islandora creators # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} ucrt {{ item }}"
      loop: "{{ lookup('file', 'templates/list_of_past_islandora_creators').splitlines() }}"

    - name: Add admin users to admin role # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} urol administrator {{ item }}"
      loop: "{{ lookup('file', 'templates/list_of_admin_users').splitlines() }}"

    - name: Add vagrant user to webserver app user group
      user: name={{ vagrant_user }}
            groups={{ webserver_app_user }}
            append=yes

    - name: Chown islandora core feature
      file:
        dest: "{{ drupal_core_path }}/modules/contrib/islandora/modules/islandora_core_feature"
        state: directory
        owner: "{{ webserver_app_user }}"
        group: "{{ webserver_app_user }}"
        mode: 0775
        recurse: yes

    - name: Chown islandora_defaults feature
      file:
        dest: "{{ drupal_core_path }}/modules/contrib/yudl_defaults"
        state: directory
        owner: "{{ webserver_app_user }}"
        group: "{{ webserver_app_user }}"
        mode: 0775
        recurse: yes

    - name: Chown controlled access terms default configuration
      file:
        dest: "{{ drupal_core_path }}/modules/contrib/controlled_access_terms/modules/controlled_access_terms_defaults"
        state: directory
        owner: "{{ webserver_app_user }}"
        group: "{{ webserver_app_user }}"
        mode: 0775
        recurse: yes

    - name: Apply patched LDAP library https://www.drupal.org/project/ldap/issues/3151284
      template:
        src: Connection.php.j2
        dest: "/var/www/html/drupal/vendor/grahl/ldap/Adapter/ExtLdap/Connection.php"
        owner: "{{ webserver_app_user }}"
        group: "{{ webserver_app_user }}"
        mode: 0755
      when: env == "staging" or env == "production"

    - name: Clear cache # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y cr"

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
      when: env == "staging" or env == "production"

    - name: Get YUDL Default Content
      git:
        repo: https://github.com/yorkulibraries/yudl_default_content.git
        dest: "{{ drupal_core_path }}/modules/contrib/yudl_default_content"
        version: main
        force: yes

    - name: Enable YUDL Default Content # noqa 301
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y en yudl_default_content"

    - name: Set YUDL front page
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y cset system.site page.front /node/1"

    - name: Add YUDL collections via islandora workbench
      command: "/opt/islandora_workbench/workbench --config /opt/workbench/configs/yudl-collections-{{ item }}.yml"
      with_items: ["00", "01", "02", "03", "04", "06", "07", "08", "09"]

    - name: Add sample objects via islandora workbench
      command: "/opt/islandora_workbench/workbench --config /opt/workbench/configs/{{ item }}.yml"
      with_items: ["paged", "single", "collection-image", "contact_categories"]
      when: not env == "production"

    - name: Add Locations menu item
      command: >
        /usr/local/bin/drush --root=/var/www/html/drupal/web ev '\Drupal\menu_link_content\Entity\MenuLinkContent::create(["title" => "Locations","link" => ["uri" => "internal:/explore/locations/a"],"menu_name" => "main","weight" => 3])->save();'

    - name: Add Subjects menu item
      command: >
        /usr/local/bin/drush --root=/var/www/html/drupal/web ev '\Drupal\menu_link_content\Entity\MenuLinkContent::create(["title" => "Subjects","link" => ["uri" => "internal:/explore/subjects/a"],"menu_name" => "main","weight" => 4])->save();'

    - name: Add Creatorss menu item
      command: >
        /usr/local/bin/drush --root=/var/www/html/drupal/web ev '\Drupal\menu_link_content\Entity\MenuLinkContent::create(["title" => "Creators","link" => ["uri" => "internal:/explore/creators/a"],"menu_name" => "main","weight" => 5])->save();'
