- src: geerlingguy.php-mysql
  version: 2.1.0

- src: geerlingguy.apache
  version: 4.0.0

- src: geerlingguy.php-versions
  version: 6.2.0

- src: geerlingguy.php
  version: 6.0.0

- src: geerlingguy.composer
  version: 1.9.2

- src: geerlingguy.git
  version: 3.0.1

- src: geerlingguy.mysql
  version: 4.3.4

- src: geerlingguy.solr
  version: 5.5.2

- src: geerlingguy.java
  version: 2.5.0

- src: geerlingguy.drupal
  version: 4.3.0

- src: geerlingguy.drush
  version: 4.0.0
