- src: geerlingguy.php-mysql
  version: 2.0.1

- src: geerlingguy.repo-epel
  version: 1.2.4

- src: geerlingguy.repo-remi
  version: 1.2.0

- src: geerlingguy.apache
  version: 3.0.0

- src: geerlingguy.php-versions
  version: 4.0.0

- src: geerlingguy.php
  version: 4.0.0

- src: geerlingguy.composer
  version: 1.7.0

- src: geerlingguy.git
  version: 2.0.2

- src: geerlingguy.mysql
  version: 3.3.0

- src: geerlingguy.postgresql
  version: 1.4.3

- src: geerlingguy.solr
  version: 4.2.1

- src: geerlingguy.java
  version: 1.10.0

- src: geerlingguy.drupal
  version: 2.5.0

- src: geerlingguy.drush
  version: 3.1.1

- src: https://github.com/yorkulibraries/ansible-role-activemq
  name: Islandora-Devops.activemq
  version: omega

- src: https://github.com/yorkulibraries/ansible-role-alpaca
  name: Islandora-Devops.alpaca
  version: yul

- src: https://github.com/yorkulibraries/ansible-role-cantaloupe
  name: Islandora-Devops.cantaloupe
  version: yul

- src: https://github.com/yorkulibraries/ansible-role-crayfish
  name: Islandora-Devops.crayfish
  version: yul

- src: https://github.com/yorkulibraries/ansible-role-drupal-openseadragon
  name: Islandora-Devops.drupal-openseadragon
  version: main

- src: https://github.com/yorkulibraries/ansible-role-fcrepo
  name: Islandora-Devops.fcrepo
  version: yul

- src: https://github.com/yorkulibraries/ansible-role-fcrepo-syn
  name: Islandora-Devops.fcrepo-syn
  version: yul

- src: https://github.com/yorkulibraries/ansible-role-tomcat8
  name: Islandora-Devops.tomcat8
  version: yul

- src: https://github.com/yorkulibraries/ansible-role-fits
  name: Islandora-Devops.fits
  version: yul

- src: https://github.com/yorkulibraries/ansible-role-grok
  name: Islandora-Devops.grok
  version: yul

- src: https://github.com/yorkulibraries/ansible-role-karaf
  name: Islandora-Devops.karaf
  version: yul

- src: https://github.com/yorkulibraries/ansible-role-keymaster
  name: Islandora-Devops.keymaster
  version: main

- src: https://github.com/yorkulibraries/ansible-role-riprap
  name: Islandora-Devops.riprap
  version: yul
