---

- hosts: tomcat
  become: yes

  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-11-jdk
    - Islandora-Devops.tomcat8
    - Islandora-Devops.fcrepo
    - Islandora-Devops.fcrepo-syn
    - Islandora-Devops.activemq
    - Islandora-Devops.fits
