---

- name: Setup, configure, and install Apache, PHP, git, composer, drush, Drupal, and OpenSeadragon
  hosts: webserver
  become: true

  pre_tasks:
    - name: Check if Drush is already installed
      stat:
        path: /var/www/html/drupal/vendor/bin/drush
      register: drush_installed

    - name: Check if Drupal Redis Service is already setup
      stat:
        path: /var/www/html/drupal/web/sites/default/redis.services.yml
      register: drupal_redis_services

    - name: Validate required variables
      assert:
        that:
          - drupal_db_name is defined
          - drupal_db_user is defined
          - drupal_db_password is defined
        fail_msg: "One or more required variables (drupal_db_name, drupal_db_user, drupal_db_password) are missing."

    - name: Create Drupal DB (mysql)
      mysql_db:
        name: "{{ drupal_db_name }}"
        state: present

    - name: Create Drupal DB User (mysql)
      mysql_user:
        name: "{{ drupal_db_user }}"
        password: "{{ drupal_db_password }}"
        priv: "{{ drupal_db_name }}.*:ALL"
        host: "%"
        state: present

  vars:
    php_version: "8.1"

  environment:
    COMPOSER_MEMORY_LIMIT: -1

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Restart PHP-FPM
      service:
        name: php-fpm
        state: restarted

  roles:
    - geerlingguy.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.git
    - role: geerlingguy.composer
      when: not drush_installed.stat.exists
    - geerlingguy.drush
    - role: geerlingguy.drupal
      when: not drupal_redis_services.stat.exists
    - perms_fix
    - Islandora-Devops.drupal-openseadragon
    - webserver_app
