---

- hosts: webserver
  become: yes

  pre_tasks:
    - name: Create Drupal DB (mysql)
      mysql_db:
        name: "{{ drupal_db_name }}"
        state: present

    - name: Create Drupal DB User (mysql)
      mysql_user:
        name: "{{ drupal_db_user }}"
        password: "{{ drupal_db_password }}"
        priv: "{{ drupal_db_name }}.*:ALL"
        host: "%"
        state: present

  vars:
    php_version: "7.4"

  environment:
    COMPOSER_MEMORY_LIMIT: -1

  roles:
    - geerlingguy.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.git
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.drupal
    - perms_fix
    - Islandora-Devops.drupal-openseadragon
    - webserver_app
      #    - Islandora-Devops.riprap
