- name: restart apache
  service:
    name: apache2
    state: restarted

- name: Install Riprap httpd config file
  template:
    src: "riprap.conf.j2"
    dest: "{{ httpd_conf_directory }}/conf-available/riprap.conf"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
    mode: 0744

- name: Symlink Riprap httpd config file into action
  file:
    src: "{{ httpd_conf_directory }}/conf-available/riprap.conf"
    dest: "{{ httpd_conf_directory_enabled }}/riprap.conf"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
    mode: 0754
    state: link
  notify: restart apache
