---

- name: Install requisite packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ crayfish_packages }}"

- name: Ensure Crayfish directory exists and has correct ownership
  file:
    path: "{{ crayfish_install_dir }}"
    state: directory
    owner: "{{ crayfish_user }}"
    group: "{{ crayfish_user }}"
    mode: "0755"
  become: true

- name: Install crayfish code
  git:
    repo: https://github.com/yorkulibraries/Crayfish.git
    dest: "{{ crayfish_install_dir }}"
    version: "{{ crayfish_version_tag }}"
    force: true
  become: true
  become_user: "{{ crayfish_user }}"

- name: Add Crayfish directory to Git's safe directory list
  command: >
    git config --local --add safe.directory {{ crayfish_install_dir }}
  args:
    chdir: "{{ crayfish_install_dir }}"
  become: true
  become_user: "{{ crayfish_user }}"
  when: crayfish_install_dir is defined

- name: Set permissions on Crayfish directory
  file:
    path: "{{ crayfish_install_dir }}"
    state: directory
    owner: "{{ crayfish_user }}"
    group: "{{ crayfish_user }}"
    recurse: true

- name: symfony/flex
  composer:
    command: config
    arguments: "--no-plugins allow-plugins.symfony/flex true"
    working_dir: "{{ crayfish_install_dir }}/{{ item }}"
  with_items: "{{ crayfish_services }}"
  become_user: "{{ crayfish_user }}"
  when: env == "production"

- name: Build crayfish code including dependencies
  composer:
    command: install
    working_dir: "{{ crayfish_install_dir }}/{{ item }}"
  with_items: "{{ crayfish_services }}"
  become_user: "{{ crayfish_user }}"

- name: Get SSL keys
  include_role:
    name: Islandora-Devops.keymaster
  vars:
    ssl_key_public_output_path: "{{ crayfish_install_dir }}/public.key"

- name: Install auth config
  template:
    src: "syn-settings.xml.j2"
    dest: "{{ crayfish_install_dir }}/syn-settings.xml"

- name: Configure crayfish code (Symfony)
  include_tasks: "./tasks/symfony_config.yml"
  with_items: "{{ crayfish_services }}"

- name: Create Islandora log dir
  file:
    path: "{{ crayfish_log_directory }}"
    state: directory
    owner: "{{ crayfish_user }}"
    group: "{{ crayfish_user }}"
    mode: "0775"

- name: Install crayfish httpd config file
  template:
    src: "httpd/{{ item }}.conf.j2"
    dest: "{{ httpd_conf_directory }}/conf-available/{{ item }}.conf"
    owner: "{{ crayfish_user }}"
    group: "{{ crayfish_user }}"
  with_items: "{{ crayfish_services }}"

- name: Symlink crayfish httpd config file into action
  file:
    src: "{{ httpd_conf_directory }}/conf-available/{{ item }}.conf"
    dest: "{{ httpd_conf_directory_enabled }}/{{ item }}.conf"
    owner: "{{ crayfish_user }}"
    group: "{{ crayfish_user }}"
    state: link
  with_items: "{{ crayfish_services }}"
  notify: restart apache
