---

- set_fact: crayfish_loop="{{ item }}"

- name: Verify/Create Symfony config directories
  file:
    state: directory
    path: '{{ crayfish_install_dir }}/{{ crayfish_loop }}/config/{{ item_path.path }}'
    mode: "0755"
    owner: "{{ crayfish_user }}"
    group: "{{ crayfish_user }}"
  with_filetree: '../templates/{{ crayfish_loop }}'
  loop_control:
    loop_var: 'item_path'
  when: item_path.state == 'directory'

- name: Template Symfony config files
  template:
    src: '{{ item_path.src }}'
    dest: '{{ crayfish_install_dir }}/{{ crayfish_loop }}/config/{{ item_path.path | regex_replace(".j2$", "") }}'
    mode: "0644"
    owner: "{{ crayfish_user }}"
    group: "{{ crayfish_user }}"
  with_filetree: '../templates/{{ crayfish_loop }}'
  loop_control:
    loop_var: item_path
  when: item_path.state == 'file'
