---

- name: Add Drupal Redis Service
  shell: "cp /var/www/html/drupal/web/modules/contrib/redis/example.services.yml /var/www/html/drupal/web/sites/default/redis.services.yml"

- name: Trusted Host Settings
  blockinfile:
    state: present
    block: |
      $settings['trusted_host_patterns'] = array(
      {% for host in drupal_trusted_hosts %}
        '{{ host }}',
      {% endfor %}
      );
      $settings['flysystem'] = [
        'fedora' => [
          'driver' => 'fedora',
          'config' => [
            'root' => '{{ fedora_base_url }}',
          ],
        ],
      ];
      $settings['redis.connection']['interface'] = 'Predis';
      $settings['redis.connection']['host'] = 'localhost';
      $settings['redis.connection']['port'] = '6379';
      $settings['cache']['default'] = 'cache.backend.redis';
      $settings['container_yamls'][] = 'sites/default/redis.services.yml';
    path: "{{ drupal_trusted_hosts_file }}"
    marker: // {mark} ANSIBLE MANAGED BLOCK

- name: Uninstall core search module
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y pm-uninstall search"
  register: uninstall_search
  changed_when: "'successfully uninstalled' in uninstall_search.stdout"

- name: Set permissions on the public files directory
  file:
    recurse: yes
    state: directory
    path: "{{ drupal_public_filesystem }}"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
    mode: 0775

- name: Create drupal configs directory.
  file:
    state: directory
    path: "{{ webserver_app_drupal_config_path }}"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
    mode: 0744

- name: Copy ldap_authentication.settings.yml
  template:
    src: "ldap_authentication.settings.yml.j2"
    dest: "{{ drupal_core_path }}/modules/contrib/yudl_defaults/config/install/ldap_authentication.settings.yml"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
    mode: 0440
  when: env == "staging" or env == "production"

- name: Copy ldap_servers.server.pydirectory.yml
  template:
    src: "ldap_servers.server.pydirectory.yml.j2"
    dest: "{{ drupal_core_path }}/modules/contrib/yudl_defaults/config/install/ldap_servers.server.pydirectory.yml"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
    mode: 0440
  when: env == "staging" or env == "production"

- name: Copy ldap_servers.settings.yml
  template:
    src: "ldap_servers.settings.yml.j2"
    dest: "{{ drupal_core_path }}/modules/contrib/yudl_defaults/config/install/ldap_servers.settings.yml"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
    mode: 0440
  when: env == "staging" or env == "production"

- name: Copy ldap_user.settings.yml
  template:
    src: "ldap_user.settings.yml.j2"
    dest: "{{ drupal_core_path }}/modules/contrib/yudl_defaults/config/install/ldap_user.settings.yml"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
    mode: 0440
  when: env == "staging" or env == "production"

- name: Import features # noqa 301
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y fim islandora_core_feature,islandora_defaults,islandora_search"

- name: Enable EVA views # noqa 301
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y ven display_media"

# pdf.js library
- name: ensure pdf.js directory exists
  file:
    path: "{{ drupal_external_libraries_directory }}/pdf.js"
    state: directory
    mode: 0754

- name: Unarchive pdf.js library
  unarchive:
    src: "https://github.com/mozilla/pdf.js/releases/download/v2.14.305/pdfjs-2.14.305-dist.zip"
    dest: "{{ drupal_external_libraries_directory }}/pdf.js"
    creates: "{{ drupal_external_libraries_directory }}/pdf.js/build"
    remote_src: yes

- name: Set permissions on libraries so we don't get a FORBIDDEN error for pdf.js
  file:
    path: "{{ drupal_core_path }}/libraries"
    state: directory
    recurse: yes
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
    mode: '1755'

- name: Add project's /vendor/bin to $PATH (ubuntu)
  lineinfile:
    path: ~/.profile
    line: 'PATH="$PATH:{{ webserver_document_root }}/drupal/vendor/bin"'
    state: present
  become: false
  when: ansible_os_family == "Debian"
