---

- name: Create JWT Key Path
  file:
    state: directory
    path: "{{ webserver_app_jwt_key_path }}"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
    mode: 0740

- name: Get SSL keys
  include_role:
    name: Islandora-Devops.keymaster
  vars:
    ssl_key_private_output_path: "{{ webserver_app_jwt_key_path }}/private.key"

- name: Create JWT Config Path
  file:
    state: directory
    path: "{{ webserver_app_jwt_config_path }}"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
    mode: 0740

- name: Copy Templated Drupal JWT Configuration
  template:
    src: "{{ item }}"
    dest: "{{ webserver_app_jwt_config_path }}/{{ item }}"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
    mode: 0740
  with_items:
    - jwt.config.yml
    - key.key.islandora_rsa_key.yml
  register: drupal_jwt_config

- name: Get YUDL Groups
  git:
    repo: https://github.com/yorkulibraries/yudl_groups.git
    dest: "{{ drupal_core_path }}/modules/contrib/yudl_groups"
    version: 2.x
    force: yes

- name: Enable YUDL Groups # noqa 301
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y en yudl_groups"

###
# Install this here since we run into a composer wanting stable over dev issue.
- name: Get Islandora Group
  git:
    repo: https://github.com/digitalutsc/islandora_group.git
    dest: "{{ drupal_core_path }}/modules/contrib/islandora_group"
    version: 2.x
    force: yes

- name: Enable Islandora Group # noqa 301
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y en islandora_group"

- name: Get Group Solr
  git:
    repo: https://github.com/yorkulibraries/group_solr.git
    dest: "{{ drupal_core_path }}/modules/contrib/group_solr"
    version: main
    force: yes

- name: Enable Group Solr # noqa 301
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y en group_solr"
###

- name: Import JWT Config Into Drupal # noqa 503
  command: "{{ drush_path }} --root {{ drupal_core_path }} config-import -y --partial --source={{ webserver_app_jwt_config_path }}"
  when: drupal_jwt_config.changed is defined and drupal_jwt_config.changed

- name: Import YUDL features moved to optional # noqa 301
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y cim --partial --source=/var/www/html/drupal/web/modules/contrib/yudl_defaults/config/optional"
