---

- include_tasks: apache.yml
  when: webserver_app_apache
  tags:
    - webserver-app
    - webserver-app-apache

- include_tasks: drupal.yml
  when: webserver_app_drupal
  tags:
    - webserver-app
    - webserver-app-drupal

- include_tasks: jwt.yml
  when: webserver_app_jwt
  tags:
    - webserver-app
    - webserver-app-jwt

- include_tasks: solr.yml
  when: webserver_app_drupal
  tags:
    - webserver-app
    - webserver-app-drupal
