---

# Comment in to build Alpaca from source
 alpaca_from_source: yes
 alpaca_version: dev
 alpaca_clone_directory: /opt/alpaca
 alpaca_karaf_repos:
  - mvn:org.apache.camel.karaf/apache-camel/2.20.4/xml/features
  - mvn:org.apache.activemq/activemq-karaf/5.15.0/xml/features
  - mvn:ca.islandora.alpaca/islandora-karaf/1.0.2/xml/features

 alpaca_milliner_base_url: "https://omega.library.yorku.ca/milliner/"
 alpaca_houdini_base_url: "https://omega.library.yorku.ca/houdini"
 alpaca_homarus_base_url: "https://omega.library.yorku.ca/homarus"
 alpaca_fits_base_url: "https://omega.library.yorku.ca/crayfits"
 alpaca_hypercube_base_url: "https://omega.library.yorku.ca/hypercube"
