---

fcrepo_syn_user: tomcat

fits_user: tomcat
fits_group: tomcat
fits_log_path: /var/log/tomcat9
fits_install_symlink: /opt/fits
fits_max_upload_file_size_MB: 75000
fits_max_request_size_MB: 75000
fit_max_in_memory_file_size_MB: 4

tomcat8_home: /var/lib/tomcat9

tomcat8_packages:
  - tomcat9
tomcat8_admin_packages:
  - tomcat9-admin

tomcat_service_name: tomcat9

tomcat8_server_user: tomcat
tomcat8_server_group: tomcat
tomcat8_user_home: /home/tomcat

tomcat8_users:
  - username: islandora
    password: "{{ islandora_tomcat_password }}"
    roles:
      - manager-gui

# For production use either "jdbc-mysql" or "jdbc-postgresql"
fcrepo_persistence: jdbc-mysql

# Set fcrepo directory structure
fcrepo_home_dir: "/omega/fcrepo"
fcrepo_allowed_external_content:
  - "https://omega.library.yorku.ca/"

# Used for mysql or postgres object persistence.
fcrepo_db_name: fcrepo
fcrepo_db_user: fcrepo
fcrepo_db_host: "127.0.0.1"
fcrepo_db_port: "3306"

fcrepo_syn_tomcat_home: "{{ tomcat8_home }}"
fcrepo_syn_default_public_key_path: "{{ fcrepo_syn_tomcat_home }}/conf/public.key"

fcrepo_syn_sites:
  - algorithm: RS256
    encoding: PEM
    anonymous: true
    default: true
    path: "{{ fcrepo_syn_default_public_key_path }}"

fcrepo_syn_tokens:
  - user: admin
    roles:
      - admin
      - fedoraAdmin
    token: "{{ islandora_syn_token }}"

fcrepo_version: "6.1.0"
fcrepo_auth_header_name: "X-Islandora"
fcrepo_syn_auth_header: "X-Islandora"
fcrepo_syn_folder: /opt/syn

cantaloupe_log_path: /var/log/cantaloupe
cantaloupe_symlink: /opt/cantaloupe
cantaloupe_FilesystemCache_pathname: /var/cache/cantaloupe
