---
composer_version: "2.1.14"
composer_version_branch: ""
composer_keep_updated: no
drupal_build_composer_project: true
drupal_composer_install_dir: /var/www/html/drupal
drupal_composer_project_options: "--prefer-dist --no-interaction"
drupal_core_owner: "{{ ansible_user }}"
drupal_composer_dependencies:
  - "drupal/devel:^5.0"
  - "drush/drush:^10.3"
  - "drupal/restui:^1.21"
  - "drupal/search_api_solr:^4.2"
  - "drupal/facets:^2"
  - "drupal/matomo:^1.21"
  - "drupal/pdf:^1.1"
  - "drupal/admin_toolbar:^3.3"
  - "drupal/rest_oai_pmh:^2.0@beta"
  - "drupal/rdf:^2.1"
  - "drupal/hal:^1.0"
  - "drupal/transliterate_filenames:^2.0"
  - "easyrdf/easyrdf:^1.1"
  - "drupal/context:^4.1"
  - "drupal/flysystem:^2@beta"
  - "drupal/jquery_ui_accordion:^2.0"
  - "drupal/typed_data:^1.0@beta"
  - "drupal/default_content:^2.0@alpha"
  - "drupal/group:^1.4"
  - "drupal/groupmedia:^2.0@alpha"
  - "drupal/group_permissions:^1.0@alpha"
  - "--with-all-dependencies drupal/rules:^3.0@alpha"
  - "islandora/islandora:^2.4"
  - "--with-all-dependencies yorkulibraries/yudl_defaults:2.x-dev islandora/openseadragon:^2 islandora/controlled_access_terms:^2"
  - "islandora/islandora_mirador:^2"
  - "islandora-rdm/islandora_fits:dev-8.x-1.x"
  - "drupal/bootstrap_barrio:^5.5"
  - "drupal/simple_sitemap:^4.1"
  - "drupal/pathauto:^1.8"
  - "drupal/views_bulk_operations:^4.2"
  - "drupal/views_bulk_edit:^2.8"
  - "drupal/search_api_autocomplete:^1.7"
  - "mjordan/islandora_repository_reports:dev-main"
  - "mjordan/islandora_workbench_integration:dev-main"
  - "drupal/cookies:^1.2"
  - "drupal/views_block_area:^1.0@beta"
  - "drupal/metatag:^1.22"
  - "drupal/term_condition:^2.0"
  - "drupal/addtoany:^2.0"
  - "drupal/twig_tweak:^3.2"
  - "drupal/block_class:^2.0"
  - "drupal/ds:^3.15"
  - "drupal/oembed_providers:^2.1"
  - "drupal/fontawesome:^2.24"
  - "drupal/views_data_export:^1.2"
  - "drupal/jquery_ui_slider:^2.0"
  - "drupal/jquery_ui_touch_punch:^1.1"
  - "yorkulibraries/yudl_customizations:1.x-dev"
  - "drupal/views_field_view:^1.0@beta"
  - "predis/predis"
  - "drupal/redis"
    #  - "drupal/views_natural_sort:^2.0@alpha"
drupal_composer_project_package: "drupal/recommended-project:^9.5@stable"
drupal_core_path: "{{ drupal_composer_install_dir }}/web"
drupal_db_user: drupal
drupal_db_name: drupal
drupal_db_backend: "{{ claw_db }}"
drupal_db_host: "127.0.0.1"
drupal_domain: "yudl.dev"
drupal_site_name: "YUDL DEV"
drupal_install_profile: standard
drupal_account_name: admin
drupal_enable_modules:
  - hal
  - rdf
  - responsive_image
  - syslog
  - serialization
  - basic_auth
  - rest
  - restui
  - rest_oai_pmh
  - devel
  - search_api_solr
  - facets
  - matomo
  - pdf
  - admin_toolbar
  - transliterate_filenames
  - islandora_defaults
  - controlled_access_terms_defaults
  - islandora_defaults
  - islandora_fits
  - islandora_breadcrumbs
  - islandora_iiif
  - islandora_search
  - simple_sitemap
  - pathauto
  - views_bulk_operations
  - views_bulk_edit
  - islandora_repository_reports
  - islandora_workbench_integration
  - islandora_mirador
  - islandora_repository_reports_log
  - islandora_repository_reports_oai_usage
  - islandora_repository_reports_matomo
  - islandora_repository_reports_activemq
  - search_api_autocomplete
  - search_api_solr_autocomplete
  - geolocation_leaflet
  - config_translation
  - locale
  - jquery_ui_accordion
  - group
  - gnode
  - rules
  - group_permissions
  - groupmedia
  - default_content
  - cookies
  - views_block_area
  - metatag
  - layout_builder
  - layout_discovery
  - media_library
  - admin_toolbar_tools
  - admin_toolbar_links_access_filter
  - term_condition
  - addtoany
  - twig_tweak
  - block_class
  - ds
  - oembed_providers
  - fontawesome
  - facets_summary
  - views_data_export
  - jquery_ui_slider
  - facets_range_widget
  - yudl_search
  - views_field_view
  - yudl_blocks
  - redis
    #  - views_natural_sort
drupal_trusted_hosts:
  - ^localhost$
  - "{{ hostvars[groups['webserver'][0]].ansible_host }}"
  - 192.168.4.5
drupal_trusted_hosts_file: "{{ drupal_core_path }}/sites/default/settings.php"
drupal_public_filesystem: "{{ drupal_core_path }}/sites/default/files"
drupal_external_libraries_directory: "{{ drupal_core_path }}/libraries"
fedora_base_url: "http://{{ hostvars[groups['tomcat'][0]].ansible_host }}:8080/fcrepo/rest/"
drupal_jsonld_remove_format: true
drupal_gemini_pseudo_bundles:
  - islandora_object:node
  - image:media
  - file:media
  - audio:media
  - video:media
openseadragon_composer_item: "islandora/openseadragon:2.x-dev"
