---

# Change selinux status to permissive
disable_selinux: yes

islandora_extra_ubuntu_packages:
  - wget
  - curl
  - htop
  - tree
  - zsh
  - fish
  - unzip
  - build-essential
  - vim
  - python3-mysqldb
  - multitail
  - silversearcher-ag
  - sendmail

islandora_extra_centos_packages:
  - wget
  - curl
  - tree
  - zsh
  - unzip
  - vim
  - make
  - automake
  - gcc
  - gcc-c++
  - kernel-devel

islandora_jwt_expiry: "1 week"

postgresql_user: postgres

# Used by both the webserver and crayfish role for CentOS.
php_enablerepo: "remi-php74"
php_packages_state: "latest"

apache_mods_enabled:
  - rewrite.load
  - proxy.load
  - proxy_http.load
  - headers.load
  - ssl.load
