---

# Change selinux status to permissive
disable_selinux: yes

islandora_extra_ubuntu_packages:
  - wget
  - curl
  - htop
  - tree
  - zsh
  - fish
  - unzip
  - build-essential
  - vim
  - python3-mysqldb
  - multitail
  - silversearcher-ag
  - acl
  - libopenjp2-tools
  - libopenjp2-7
  - libopenjp2-7-dev
  - libjpeg62-dev
  - libtiff-dev
  - libpng-dev
  - libwebp-dev
  - librsvg2-dev
  - libjpeg-dev
  - libjpeg-turbo8-dev
  - libjpeg8-dev
  - libtiff5-dev
  - libtiffxx5
  - libexif-dev
  - zlib1g-dev
  - ffmpeg
  - graphicsmagick
  - libturbojpeg-dev

islandora_jwt_expiry: "1 week"

# Used by both the webserver and crayfish role for CentOS.
php_enablerepo: "remi-php80"
php_packages_state: "latest"

apache_mods_enabled:
  - rewrite
  - proxy
  - proxy_http
  - headers
  - ssl
