- name: Create Apache config for CrayFits
  blockinfile:
    path: "{{ httpd_conf_directory }}/conf-available/CrayFits.conf"
    create: yes
    block: |
      Alias "/crayfits" "{{ crayfits_home }}/CrayFits/public"
      <Directory "{{ crayfits_home }}/CrayFits/public">
        FallbackResource /crayfits/index.php
        Require all granted
        DirectoryIndex index.php
        SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
      </Directory>

- name: Enable CrayFits site
  file:
    src: "{{ httpd_conf_directory }}/conf-available/CrayFits.conf"
    dest: "{{ httpd_conf_directory_enabled}}/CrayFits.conf"
    state: link

- name: Set ownership on CrayFits home
  file:
    path: "{{ crayfits_home }}"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"

- name: "Get git config global safe directories dir"
  shell: "git config --global --get-all safe.directory || echo ''"
  register: "__git_config_global_safe_dir"

- name: "Set Fixity source directory as git safe dir"
  command: "git config --global --add safe.directory {{ crayfits_home }}/CrayFits"
  when:
    - crayfits_home + '/CrayFits' not in __git_config_global_safe_dir.stdout_lines

- name: Get CrayFits from Github
  git:
    repo: https://github.com/roblib/CrayFits.git
    dest: "{{ crayfits_home }}/CrayFits"
    force: yes

- name: Change CrayFits directory ownership, group and permissions
  file:
    path: "{{ crayfits_home }}/CrayFits"
    state: directory
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
    recurse: true

- name: Run Composer on CrayFits
  composer:
    command: install
    working_dir: "{{ crayfits_home }}/CrayFits"
  become_user: "{{ crayfish_user }}"


- name: restart apache
  service:
    name: "{{ apache_service }}"
    state: restarted
