---

- name: Create FITS destination dir
  file:
    path: "{{ fits_install_root }}/fits-{{ fits_version }}"
    state: directory
    owner: "{{ fits_user }}"
    group: "{{ fits_group }}"
    mode: "0700"

- name: Downloading FITS executables
  get_url:
    url: "{{ fits_src_url }}"
    dest: "{{ fits_install_root }}/fits-{{ fits_version }}"
    mode: "0755"
    checksum: "{{ fits_zip_md5sum }}"
    force: false
  retries: 5
  register: result
  until: result is succeeded

- name: Unzip FITS
  unarchive:
    src: "{{ fits_install_root }}/fits-{{ fits_version }}/fits-{{ fits_version }}.zip"
    dest: "{{ fits_install_root }}/fits-{{ fits_version }}"
    remote_src: true
    creates: "{{ fits_install_root }}/fits-{{ fits_version }}/fits.sh"

- name: Remove temporary FITS directory
  file:
    path: /opt/fits
    state: absent

- name: Ensure FITS symlink is correct
  file:
    state: link
    src: "{{ fits_install_root }}/fits-{{ fits_version }}"
    dest: "{{ fits_install_symlink }}"
  register: fits_symlink

- name: Move FITS into place
  file:
    state: link
    src: "{{ fits_install_root }}/fits-{{ fits_version }}"
    dest: "{{ fits_install_symlink }}"
    owner: "{{ fits_user }}"
    group: "{{ fits_group }}"
  when: fits_symlink is changed
