- include_tasks: install.yml
  tags:
    - fcrepo
    - fcrepo-install

- include_tasks: db-mysql.yml
  when: fcrepo_persistence == 'jdbc-mysql'
  tags:
    - fedora
    - fedora-install
    - fedora-db

- include_tasks: config.yml
  tags:
    - fcrepo
    - fcrepo-config
