---

- name: Download and unarchive
  unarchive:
    remote_src: yes
    src: http://archive.apache.org/dist/activemq/{{ activemq_version }}/apache-activemq-{{ activemq_version }}-bin.tar.gz
    dest: "{{ activemq_install_root }}"
    owner: "{{ activemq_user }}"
    creates: "{{ activemq_install_root }}/activemq"

- name: Move activemq
  command: mv "{{ activemq_install_root }}/apache-activemq-{{ activemq_version }}" "{{ activemq_install_root }}/activemq"
  args:
    creates: "{{ activemq_install_root }}/activemq"

- name: Remove jetty-realm.properties
  file:
    path: "{{ activemq_install_root }}/activemq/conf/jetty-realm.properties"
    state: absent

- name: Set ActiveMQ admin password
  template:
    src: "jetty-realm.properties.j2"
    dest: "{{ activemq_install_root }}/activemq/conf/jetty-realm.properties"

# Transitional removal of old-style init.d symlink
# This task can be removed in the future.
- name: Remove init.d symlink
  file:
    path: /etc/init.d/activemq
    state: absent

- name: Create systemd unit
  template:
    src: activemq.service.j2
    dest: /etc/systemd/system/activemq.service

- name: Reload systemd
  systemd:
    daemon-reload: yes
    enabled: yes
    state: started
    name: activemq
