---

fcrepo_syn_user: tomcat

fits_user: tomcat
fits_group: tomcat
fits_log_path: /var/log/tomcat9
fits_install_symlink: /opt/fits
fits_max_upload_file_size_MB: 4000
fits_max_request_size_MB: 4000
fit_max_in_memory_file_size_MB: 4

tomcat_home: /var/lib/tomcat9

tomcat_packages:
  - tomcat9
  - libopenjp2-tools
tomcat_admin_packages:
  - tomcat9-admin

tomcat_service_name: tomcat9

tomcat_server_user: tomcat
tomcat_server_group: tomcat
tomcat_user_home: /home/tomcat

tomcat_users:
  - username: islandora
    password: "{{ islandora_tomcat_password }}"
    roles:
      - manager-gui

# For production use either "jdbc-mysql" or "jdbc-postgresql"
#fcrepo_persistence: file-simple
fcrepo_persistence: jdbc-mysql

# Used for mysql or postgres object persistence.
fcrepo_home_dir: /opt/fcrepo
fcrepo_db_name: fcrepo
fcrepo_db_user: fcrepo
fcrepo_db_host: "127.0.0.1"
fcrepo_db_port: "3306"
fcrepo_allowed_external_content:
  - http://localhost:8000/
fcrepo_allowed_external_content_file: "{{ fcrepo_home_dir }}/allowed-external-content.txt"

fcrepo_syn_tomcat_home: "{{ tomcat_home }}"
fcrepo_syn_default_public_key_path: "{{ fcrepo_syn_tomcat_home }}/conf/public.key"

fcrepo_syn_sites:
  - algorithm: RS256
    encoding: PEM
    anonymous: true
    default: true
    path: "{{ fcrepo_syn_default_public_key_path }}"

fcrepo_syn_tokens:
  - user: admin
    roles:
      - admin
      - fedoraAdmin
    token: "{{ islandora_syn_token }}"

fcrepo_version: "6.4.1"
fcrepo_auth_header_name: "X-Islandora"
fcrepo_syn_auth_header: "X-Islandora"
fcrepo_syn_folder: /opt/syn

cantaloupe_deploy_war: yes
cantaloupe_deploy_war_path: "{{ tomcat_home }}/webapps"
cantaloupe_user: tomcat
cantaloupe_group: tomcat
cantaloupe_admin_enabled: "true"
cantaloupe_OpenJpegProcessor_path_to_binaries: /usr/bin
cantaloupe_log_application_ConsoleAppender_enabled: "false"
cantaloupe_log_application_FileAppender_enabled: "true"
cantaloupe_log_application_FileAppender_pathname: "{{ cantaloupe_log_path }}/application.log"
cantaloupe_log_access_FileAppender_enabled: "true"
cantaloupe_log_access_FileAppender_pathname: "{{ cantaloupe_log_path }}/access.log"
cantaloupe_FilesystemResolver_BasicLookupStrategy_path_prefix: /var/www/html/drupal/web/
cantaloupe_processor_jp2: KakaduDemoProcessor
cantaloupe_cache_source: FilesystemCache
cantaloupe_cache_derivative: FilesystemCache
cantaloupe_create_FilesystemCache_dir: yes
cantaloupe_resolver_static: HttpSource2
cantaloupe_HttpResolver_BasicLookupStrategy_url_prefix: ""
cantaloupe_symlink: /opt/cantaloupe
cantaloupe_log_path: /var/log/cantaloupe
cantaloupe_FilesystemCache_pathname: /var/cache/cantaloupe
cantaloupe_processor_selection_strategy: ManualSelectionStrategy
cantaloupe_StreamProcessor_retrieval_strategy: CacheStrategy
cantaloupe_processor_fallback_retrieval_strategy: CacheStrategy
cantaloupe_KakaduProcessor_path_to_binaries: /opt/kakadu
cantaloupe_processor_tif: ImageMagickProcessor
