---

  - name: Check if files directory is already moved
    stat:
      path: /tank/data/drupal/files
    register: files_dir
    when: env == "production"

  - name: Move existing files sites/default/files
    command: rsync -a --remove-source-files "{{ drupal_core_path }}"/sites/default/files/* /tank/data/drupal/files
    when: env == "production"and not files_dir.stat.exists

  - name: Remove sites/default/files
    file:
      path: "{{ drupal_core_path }}/sites/default/files"
      state: absent
    when: env == "production" and not files_dir.stat.exists

  - name: Check if the symlink exists
    stat:
      path: "{{ drupal_core_path }}/sites/default/files"
    register: files_symlink

  - name: Link PRODUCTION Drupal files directory
    file:
      src: /tank/data/drupal/files
      dest: "{{ drupal_core_path }}/sites/default/files"
      state: link
    when: env == "production" and not files_symlink.stat.islnk

  - name: Ensure symlink ownership and permissions
    file:
      path: "{{ drupal_core_path }}/sites/default/files"
      owner: "{{ webserver_app_user }}"
      group: "{{ webserver_app_user }}"
      mode: "0775"
      state: directory
    when: env == "production"

  - name: Ensure correct permissions for default.services.yml
    file:
      state: directory
      path: "{{ drupal_core_path }}/sites/default"
      owner: "{{ webserver_app_user }}"
      group: "{{ webserver_app_user }}"
      mode: "1777"
