---

webserver_app_apache: yes
webserver_app_drupal: yes
webserver_app_jwt: yes

webserver_app_jwt_key_path: /opt/islandora/auth
webserver_app_jwt_config_path: /opt/islandora/configs/jwt

webserver_app_drupal_config_path: /opt/islandora/configs/drupal

webserver_app_user: www-data
solr_user: solr
solr_instance_conf_path: /var/solr/data/{{ solr_cores[0] }}/conf

webserver_document_root: /var/www/html
