---

webserver_app_apache: yes
webserver_app_drupal: yes
webserver_app_jwt: yes

webserver_app_jwt_key_path: /opt/islandora/auth
webserver_app_jwt_config_path: /opt/islandora/configs/jwt

webserver_app_drupal_config_path: /opt/islandora/configs/drupal

webserver_app_user: www-data
solr_user: solr
solr_instance_conf_path: /var/solr/data/{{ solr_cores[0] }}/conf

webserver_document_root: /var/www/html

apache_mpm_event_start_servers: 5
apache_mpm_event_min_spare_threads: 125
apache_mpm_event_max_spare_threads: 150
apache_mpm_event_thread_limit: 25
apache_mpm_event_threads_per_child: 25
apache_mpm_event_max_request_workers: 150
apache_mpm_event_max_connections_per_child: 0
