---

apache_listen_port: 80
apache_create_vhosts: true
apache_vhosts_filename: "islandora.conf"
apache_remove_default_vhost: true
apache_vhosts:
  - servername: "{{ hostvars[groups['webserver'][0]].ansible_host }}"
    documentroot: "/var/www/html/drupal/web"
    allow_override: All
    options: -Indexes +FollowSymLinks

apache_mods_enabled:
  - rewrite
  - proxy
  - proxy_http
  - proxy_fcgi
  - headers
  - ssl
  - setenvif
  - mpm_event

apache_mods_disabled:
  - "php{{ php_version }}"
  - mpm_prefork
