---

- name: Ensure composer working directory exists
  file:
    path: "{{ openseadragon_composer_root }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Check if OpenSeadragon is already installed with composer
  stat:
    path: "{{ openseadragon_composer_root }}/vendor/openseadragon"
  register: openseadragon_composer_installed

- name: Install OpenSeadragon with composer
  composer:
    command: require
    arguments: "{{ openseadragon_composer_item }}"
    working_dir: "{{ openseadragon_composer_root }}"
  become: true
  become_user: "{{ ansible_user }}"
  when: not openseadragon_composer_installed.stat.exists

- name: Ensure parent directory for library exists
  file:
    path: "{{ openseadragon_composer_root }}/web/sites/all/assets/vendor"
    state: directory
    mode: "0755"

- name: Ensure OpenSeadragon Library Exists
  stat:
    path: "{{ openseadragon_composer_root }}/web/sites/all/assets/vendor/openseadragon"
  register: openseadragon_library_dir

- name: Ensure temporary directory exists
  file:
    path: "{{ openseadragon_temp_folder }}"
    state: directory
    mode: "0755"

- name: Unarchive OpenSeadragon library
  unarchive:
    remote_src: true
    src: https://github.com/openseadragon/openseadragon/releases/download/v{{ openseadragon_version }}/openseadragon-bin-{{ openseadragon_version }}.tar.gz
    dest: "{{ openseadragon_temp_folder }}"
  when: not openseadragon_library_dir.stat.exists

- name: Move OpenSeadragon library into place
  file:
    src: "{{ openseadragon_temp_folder }}/openseadragon-bin-{{ openseadragon_version }}"
    dest: "{{ openseadragon_composer_root }}/web/sites/all/assets/vendor/openseadragon"
    state: directory
  when: not openseadragon_library_dir.stat.exists

- name: Clean up temporary directory
  file:
    path: "{{ openseadragon_temp_folder }}"
    state: absent
  when: not openseadragon_library_dir.stat.exists
