---

- name: Use drush_path if defined
  set_fact: openseadragon_drush_path="{{ drush_path }}"
  when: drush_path != ''

- include_tasks: install.yml
  tags:
    - openseadragon
    - openseadragon-install

- include_tasks: config.yml
  tags:
    - openseadragon
    - openseadragon-config
